### PR TITLE
Revert "Update to resolver 20.11"

### PR DESCRIPTION
**Pull request by iHiD**
Reverts exercism/haskell-test-runner#72

### CODE REVIEW

**Comment by iHiD** [comment]
@ErikSchierboom Can you revert this revert tomorrow pls. This deploy caused the machines to run out of HDD space so I reverted it. Not anyone's fault (other than mine really) but reverting was the quickest solution. As a note, this image is huge though (5GB) compared to other that are like 200MB.

**Comment by MatthijsBlom** [comment]
This revert broke all exercises on the Haskell track again.

I guess this could (largely) be fixed by reverting https://github.com/exercism/haskell/pull/1158 as well, but seeing as this one will be reverted tomorrow it's probably not worth the hassle.

**Comment by ErikSchierboom** [comment]
@MatthijsBlom Is there any way in which we can reduce the image size? In particular, we're running `stack build --resolver lts-20.18 --no-terminal --test --no-run-tests` beforehand to pre-compile/download any extra dependencies.

**Comment by MatthijsBlom** [comment]
I hardly know anything about what an image is, or what the test runner even does. I'd need to read up / be explained.

However,

> In particular, we're running `stack build --resolver lts-20.18 --no-terminal --test --no-run-tests` beforehand to pre-compile/download any extra dependencies.

Do I understand correctly that you are 'pre-compiling' the allowed dependencies _every time_?

**Comment by ErikSchierboom** [comment]
No, we're precompiling them once when we build the image

**Pull request merged**
